-- QĐ1: Tuổi học sinh từ 15 đến 20.
ALTER TABLE HOCSINH ADD CONSTRAINT CK_TUOI CHECK( YEAR(NgaySinh) >=2000 and  YEAR(NgaySinh) <= 2005 ) 
GO

-- QĐ2: Có 3 khối lớp (10, 11, 12). Khối 10 có 4 lớp (10A1, 10A2, 10A3, 10A4). Khối 11 có 3 lớp (11A1, 11A2, 11A3). Khối 12 có 2 lớp (12A1, 12A2). Mỗi lớp không quá 40 học sinh
ALTER TABLE KHOI ADD CONSTRAINT CK_SLKHOI CHECK(MaKhoi IN ('K10', 'K11', 'K12')) 
GO


-- QĐ4: Có 2 học kỳ (I, II). Có 9 môn học (Toán, Lý, Hóa, Sinh, Sử, Địa, Văn, Đạo Đức, Thể Dục). 0 <= Điểm <= 10
ALTER TABLE HOCKY ADD CONSTRAINT CK_SLHK CHECK(MaHK IN ('HK1', 'HK2')) 
GO

ALTER TABLE MONHOC ADD CONSTRAINT CK_SLMH CHECK(MaMH IN ('01','02','03','04','05','06','07','08')) 
GO

ALTER TABLE BANGDIEM ADD CONSTRAINT CK_DIEM CHECK(
	Diem15p BETWEEN 0 AND 10 AND
	LEN(SUBSTRING(CAST(Diem15p AS VARCHAR), CHARINDEX('.', Diem15p) + 1, 1000)) >= 2
)
GO

ALTER TABLE BANGDIEM ADD CONSTRAINT CK_DIEM1 CHECK(
	Diem1Tiet BETWEEN 0 AND 10 AND
	LEN(SUBSTRING(CAST(Diem1Tiet AS VARCHAR), CHARINDEX('.', Diem1Tiet) + 1, 1000)) >= 2
)
GO

ALTER TABLE BANGDIEM ADD CONSTRAINT CK_DIEM2 CHECK(
	DiemTB BETWEEN 0 AND 10 AND
	LEN(SUBSTRING(CAST(DiemTB AS VARCHAR), CHARINDEX('.', DiemTB) + 1, 1000)) >= 2
)
GO

-- QĐ5: Học sinh đạt môn nếu có điểm trung bình >= 5. ALTER TABLE HOCSINH ADD CONSTRAINT CK_GIOITINH CHECK(GioiTinh IN ('Nam', 'Nữ')) 
GO



